#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.5.0
// Descriptor size: 37 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 8 |
// +----------+-------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x05, 0x01,    // UsagePage(Generic Desktop[0x0001])
    0x09, 0x06,    // UsageId(Keyboard[0x0006])
    0xA1, 0x01,    // Collection(Application)
    0x85, 0x01,    //     ReportId(1)
    0x05, 0x07,    //     UsagePage(Keyboard/Keypad[0x0007])
    0x19, 0xE0,    //     UsageIdMin(Keyboard LeftControl[0x00E0])
    0x29, 0xE7,    //     UsageIdMax(Keyboard Right GUI[0x00E7])
    0x15, 0x00,    //     LogicalMinimum(0)
    0x25, 0x01,    //     LogicalMaximum(1)
    0x95, 0x08,    //     ReportCount(8)
    0x75, 0x01,    //     ReportSize(1)
    0x81, 0x02,    //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x19, 0x01,    //     UsageIdMin(ErrorRollOver[0x0001])
    0x29, 0x65,    //     UsageIdMax(Keyboard Application[0x0065])
    0x15, 0x01,    //     LogicalMinimum(1)
    0x25, 0x65,    //     LogicalMaximum(101)
    0x75, 0x07,    //     ReportSize(7)
    0x81, 0x00,    //     Input(Data, Array, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,          // EndCollection()
};

#pragma pack(push,1)

#define HID_REPORT_INPUT1_ID (1)
struct HidReportInput1
{
    uint8_t ReportId = HID_REPORT_INPUT1_ID;
    uint8_t Payload[8];
};

#pragma pack(pop)